services:

  introDocker: # container 1 - e suas informações
    image: postgres
    container_name: docker # podemos escolher qualquer nome
    environment: # variaveis do arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5436:5432" #o primeiro se refere a dentro do container e o segundo a que esta fora.

  api:
    build:
     context: .
     dockerfile: Dockerfile.api 
    container_name: produtos-api
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
         #{lado de dentro} #{lado de fora(onde vai realmente acessar apartir do pc)}
    depends_on:   #esse serviço, depende desse: 
      - introDocker
    environment: #variaveis que estão no .env
       DATABASE_URL: ${DATABASE_URL_CONTAINER}
    command: sh -c "npx prisma migrate deploy && npm run start:prod" #comando a executar quando configurar tudo

    